language: go
go:
  - 1.7

go_import_path: github.com/kubernetes-incubator/spartakus

sudo: required

services:
  - docker

jobs:
  include:
    - stage: Build
      script: make all
    - stage: Test
      script: make test
